apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: testservice2
spec: 
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: testservice2
    spec: 
      containers: 
        - name: testservice2 
          image: "192.168.0.128:5000/testservice:1.0.0-RC1"
          ports: 
            - containerPort: 5000

---
apiVersion: v1
kind: Service 
metadata: 
  name: testservice2
spec: 
  ports: 
    - port: 30001
      targetPort: 5000 
      protocol: TCP 
  type: NodePort
  selector: 
    app: testservice2            