apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: testservice3
spec: 
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: testservice3
    spec: 
      containers: 
        - name: testservice3
          image: "192.168.0.128:5000/testservice:1.0.0-RC3"
          ports: 
            - containerPort: 5000
---
apiVersion: v1
kind: Service 
metadata: 
  name: testservice3
spec: 
  ports: 
    - port: 5000
      targetPort: 5000 
      protocol: TCP 
      nodePort: 30003
  type: NodePort
  selector: 
    app: testservice3