apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: testservice1
spec: 
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: testservice1
    spec: 
      containers: 
        - name: testservice1 
          image: "192.168.0.128:5000/testservice:1.0.0-RC1"
          ports: 
            - containerPort: 5000
---
apiVersion: v1
kind: Service 
metadata: 
  name: testservice1
spec: 
  ports: 
    - port: 5000
      targetPort: 5000 
      protocol: TCP 
      nodePort: 30001
  type: NodePort
  selector: 
    app: testservice1            